dist: trusty
sudo: required
language: python

python:
  - '3.6'

services:
  - postgresql: '9.5'
  - redis-server
  - docker

env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost:5432
    - REDIS_URL=redis://localhost:6379
    - S3_BUCKET=odooku
    - S3_ENDPOINT_URL=http://localhost:4569
    - S3_CUSTOM_DOMAIN=http://odooku.localhost:4569
    - AWS_ACCESS_KEY_ID=foobar
    - AWS_SECRET_ACCESS_KEY=foobar

install:
  - sudo apt-get install libpq-dev libxml2-dev libxslt1-dev libldap2-dev libsasl2-dev
    libssl-dev nodejs npm pandoc
  - pip install -r requirements.travis.txt
  - pip install -r requirements.dev.txt
  - python setup.py bdist_wheel
  - pip install --find-links file://$(pwd)/dist odooku
  - sudo npm install -g less

before_script:
  - docker run --name s3 -p 4569:4569 -d lphoward/fake-s3:latest -r /fakes3_root -p 4569 -H localhost

script:
  - odooku runtests --db-name test

deploy:
  skip_cleanup: true
  provider: script
  script:
    - twine upload dist/*
  on:
    tags: true